import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import vitePluginImportMap from './vite-plugin-importmap';

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vitePluginImportMap({
      extraExclude: [],
      mapping: {
        "scheduler": "https://esm.sh/scheduler@0.25.0",
        "react": "https://esm.sh/react@19.0.0",
        "react-is": "https://esm.sh/react-is@19.0.0",
        "react-transition-group": "https://esm.sh/react-transition-group@4.4.5?deps=react-dom@19.0.0,react@19.0.0,dom-helpers@5.2.1",
        "react/jsx-runtime": "https://esm.sh/react/jsx-runtime",
        "prop-types": "https://esm.sh/prop-types@15.8.1",
        "clsx": "https://esm.sh/clsx@2.1.1",
        "react-dom": "https://esm.sh/react-dom@19.0.0",
        "react-dom/client": "https://esm.sh/react-dom@19.0.0/client",
        "dom-helpers/addClass": "https://esm.sh/dom-helpers@5.2.1/addClass",
        "dom-helpers/removeClass": "https://esm.sh/dom-helpers@5.2.1/removeClass",
        "hoist-non-react-statics": "https://esm.sh/hoist-non-react-statics@3.3.2?deps=react-is@19.0.0",
        "stylis": "https://esm.sh/stylis@4.3.5",
        "@mui/private-theming": "https://esm.sh/@mui/private-theming@6.4.1?deps=@mui/utils@6.4.1",
        "@mui/material/utils": "https://esm.sh/@mui/material@6.4.1/utils",
        "@mui/material/Box": "https://esm.sh/@mui/material@6.4.1/Box?deps=@mui/system@6.4.1,@mui/utils@6.4.1,prop-types@15.8.1,react@19.0.0",
        "@mui/material/Button": "https://esm.sh/@mui/material@6.4.1/Button?deps=@mui/system@6.4.1,@mui/utils@6.4.1,prop-types@15.8.1,react@19.0.0",
        "@mui/material/Typography": "https://esm.sh/@mui/material@6.4.1/Typography?deps=@mui/system@6.4.1,@mui/utils@6.4.1,prop-types@15.8.1,react@19.0.0",
        "@mui/utils": "https://esm.sh/@mui/utils@6.4.1?deps=react-is@19.0.0",
        "@mui/utils/resolveProps": "https://esm.sh/@mui/utils@6.4.1/resolveProps",
        "@mui/utils/composeClasses": "https://esm.sh/@mui/utils@6.4.1/composeClasses",
        "@mui/utils/formatMuiErrorMessage": "https://esm.sh/@mui/utils@6.4.1/formatMuiErrorMessage",
        "@mui/utils/clamp": "https://esm.sh/@mui/utils@6.4.1/clamp",
        "@mui/utils/getDisplayName": "https://esm.sh/@mui/utils@6.4.1/getDisplayName",
        "@mui/utils/ClassNameGenerator": "https://esm.sh/@mui/utils@6.4.1/ClassNameGenerator",
        "@mui/utils/createChainedFunction": "https://esm.sh/@mui/utils@6.4.1/createChainedFunction",
        "@mui/utils/generateUtilityClasses": "https://esm.sh/@mui/utils@6.4.1/generateUtilityClasses",
        "@mui/utils/generateUtilityClass": "https://esm.sh/@mui/utils@6.4.1/generateUtilityClass",
        "@mui/utils/debounce": "https://esm.sh/@mui/utils@6.4.1/debounce",
        "@mui/utils/deprecatedPropType": "https://esm.sh/@mui/utils@6.4.1/deprecatedPropType",
        "@mui/utils/isMuiElement": "https://esm.sh/@mui/utils@6.4.1/isMuiElement",
        "@mui/utils/ownerDocument": "https://esm.sh/@mui/utils@6.4.1/ownerDocument",
        "@mui/utils/ownerWindow": "https://esm.sh/@mui/utils@6.4.1/ownerWindow",
        "@mui/utils/requirePropFactory": "https://esm.sh/@mui/utils@6.4.1/requirePropFactory",
        "@mui/utils/setRef": "https://esm.sh/@mui/utils@6.4.1/setRef",
        "@mui/utils/useEnhancedEffect": "https://esm.sh/@mui/utils@6.4.1/useEnhancedEffect",
        "@mui/utils/useId": "https://esm.sh/@mui/utils@6.4.1/useId",
        "@mui/utils/unsupportedProp": "https://esm.sh/@mui/utils@6.4.1/unsupportedProp",
        "@mui/utils/useControlled": "https://esm.sh/@mui/utils@6.4.1/useControlled",
        "@mui/utils/useEventCallback": "https://esm.sh/@mui/utils@6.4.1/useEventCallback",
        "@mui/utils/useForkRef": "https://esm.sh/@mui/utils@6.4.1/useForkRef",
        "@mui/utils/styleFunctionSx": "https://esm.sh/@mui/utils@6.4.1/styleFunctionSx",
        "@mui/utils/exactProp": "https://esm.sh/@mui/utils@6.4.1/exactProp",
        "@mui/utils/refType": "https://esm.sh/@mui/utils@6.4.1/refType",
        "@mui/utils/capitalize": "https://esm.sh/@mui/utils@6.4.1/capitalize",
        "@mui/utils/deepmerge": "https://esm.sh/@mui/utils@6.4.1/deepmerge",
        "@mui/utils/elementTypeAcceptingRef": "https://esm.sh/@mui/utils@6.4.1/elementTypeAcceptingRef",
        "@mui/utils/elementAcceptingRef": "https://esm.sh/@mui/utils@6.4.1/elementAcceptingRef",
        "@mui/utils/isFocusVisible": "https://esm.sh/@mui/utils@6.4.1/isFocusVisible",
        "@mui/utils/useLazyRef": "https://esm.sh/@mui/utils@6.4.1/useLazyRef",
        "@mui/utils/useTimeout": "https://esm.sh/@mui/utils@6.4.1/useTimeout",
        "@mui/utils/chainPropTypes": "https://esm.sh/@mui/utils@6.4.1/chainPropTypes",
        "@mui/system": "https://esm.sh/@mui/system@6.4.1?deps=@mui/utils@6.4.1,@mui/styled-engine@6.4.0,@mui/private-theming@6.4.1,prop-types@15.8.1,react@19.0.0",
        "@mui/system/colorManipulator": "https://esm.sh/@mui/system@6.4.1/colorManipulator?deps=@mui/utils@6.4.1",
        "@mui/system/styleFunctionSx": "https://esm.sh/@mui/system@6.4.1/styleFunctionSx?deps=@mui/utils@6.4.1",
        "@mui/system/spacing": "https://esm.sh/@mui/system@6.4.1/spacing?deps=@mui/utils@6.4.1",
        "@mui/system/cssVars": "https://esm.sh/@mui/system@6.4.1/cssVars?deps=@mui/utils@6.4.1",
        "@mui/system/createTheme": "https://esm.sh/@mui/system@6.4.1/createTheme?deps=@mui/utils@6.4.1",
        "@mui/system/createStyled": "https://esm.sh/@mui/system@6.4.1/createStyled?deps=@mui/utils@6.4.1",
        "@mui/system/DefaultPropsProvider": "https://esm.sh/@mui/system@6.4.1/DefaultPropsProvider?deps=@mui/utils@6.4.1",
        "@mui/system/createBreakpoints": "https://esm.sh/@mui/system@6.4.1/createBreakpoints?deps=@mui/utils@6.4.1",
        "@mui/system/useThemeProps": "https://esm.sh/@mui/system@6.4.1/useThemeProps?deps=@mui/utils@6.4.1",
        "@mui/system/InitColorSchemeScript": "https://esm.sh/@mui/system@6.4.1/InitColorSchemeScript?deps=@mui/utils@6.4.1",
        "@mui/styled-engine": "https://esm.sh/@mui/styled-engine@6.4.0?deps=@emotion/react@11.11.4,@emotion/styled@11.14.0",
        "@emotion/react": "https://esm.sh/@emotion/react@11.11.4?deps=@emotion/cache@11.14.0,hoist-non-react-statics@3.3.2",
        "@emotion/styled": "https://esm.sh/@emotion/styled@11.14.0?deps=@emotion/is-prop-valid@1.3.1,@emotion/serialize@1.3.3,@emotion/react@11.11.4",
        "@emotion/serialize": "https://esm.sh/@emotion/serialize@1.3.3?deps=@emotion/hash@0.9.2",
        "@emotion/use-insertion-effect-with-fallbacks": "https://esm.sh/@emotion/use-insertion-effect-with-fallbacks@1.2.0",
        "@emotion/utils": "https://esm.sh/@emotion/utils@1.4.2",
        "@emotion/is-prop-valid": "https://esm.sh/@emotion/is-prop-valid@1.3.1",
        "@emotion/hash": "https://esm.sh/@emotion/hash@0.9.2",
        "@emotion/unitless": "https://esm.sh/@emotion/unitless@0.10.0",
        "@emotion/memoize": "https://esm.sh/@emotion/memoize@0.9.0",
        "@emotion/cache": "https://esm.sh/@emotion/cache@11.14.0",
        "@emotion/weak-memoize": "https://esm.sh/@emotion/weak-memoize@0.4.0",
        "@emotion/sheet": "https://esm.sh/@emotion/sheet@1.4.0"
      },
    }),
    react(),
  ],
})
